### ISSUE TITLE
Main menu categories

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Zemma-Hammerman-Site#14]
Please make the main menu categories clickable.

**Comment by MeanEYE** [comment]
Can you explain, for the purposes of historical record, what should happen on click. To my knowledge they want to go directly to the project when project name is clicked on main menu:
![image](https://user-images.githubusercontent.com/1911594/29170641-e657f784-7dd9-11e7-9f54-25673531a132.png)

@hanan-avzuk please confirm as well.

**Comment by hanan-avzuk** [comment]
![zhg](https://user-images.githubusercontent.com/18681483/29171287-b2e875b2-7de4-11e7-89d4-d935ddecad56.png)
At the top there is a go to the project link - nobody sees it and its not useful !
Above the round menu appears the project name: either that should be a link and a visible and understandable one OR htere should be a button saying " to the project" near, below the project title.

**Comment by MeanEYE** [comment]
Thought as much. We have couple of solutions here, though I doubt they will listen to any of them, starting with making the arrows near project tile something else other than text. The reason why no one clicks on that stupid thing is because it doesn't look like a button and their designers are _clueless_ about design language and UX. We could just make those `<<` appear as button while the rest of the title remains the same. This doesn't change functionality as it is right now, but design will give a hint to people it's actually a button. For example we could use this
![image](https://user-images.githubusercontent.com/1911594/29172696-0c239868-7de1-11e7-8c2f-62ce8e856b86.png)
style of buttons for that. Further more we can drive attention by slightly fading in an out that button on project change. That way users will notice it easily, button will look like button and we might even do some animation as main menu is not really useful and we want to incentivize people to go visit other pages which is sort of counter-productive considering how convoluted and hidden their design is.

Second approach would be to use the same style and move project name a bit up over the image. Show the button in bright read on project change. Same behavior.

I am open to any other suggestions as long as they don't involve huge number of changes as this code is already somewhat convoluted.

**Comment by hanan-avzuk** [comment]
Either make project name a button or put a button under it and make both the project name and the button lead to the same place. The top thing, where is says "to the project" can stay as is, since noone touches it anyhow and noone knows of its existence.

**Comment by MeanEYE** [comment]
Ah, okay so top, circled thing, is "to the project" and not the project name itself.  Okay, I'll think of a solution that will work.
